In [32]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,3])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([3,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)

multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
op=np.array([[0],[0],[0],[0],[0],[0],[0],[1]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for AND GATE")
    result=np.around(sess.run(z,feed_dict={x:inp}))
    print (result.astype(np.int64))

iteration=  0 cost=  0.440967
iteration=  1000 cost=  0.272631
iteration=  2000 cost=  0.247425
iteration=  3000 cost=  0.227704
iteration=  4000 cost=  0.211645
iteration=  5000 cost=  0.198228
iteration=  6000 cost=  0.18679
iteration=  7000 cost=  0.176879
iteration=  8000 cost=  0.168177
iteration=  9000 cost=  0.160452
iteration=  10000 cost=  0.15353
iteration=  11000 cost=  0.147278
iteration=  12000 cost=  0.141593
Validating output for AND GATE
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]]


In [31]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,3])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([3,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
op=np.array([[0],[1],[1],[1],[1],[1],[1],[1]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for OR GATE")
    result=np.around(sess.run(z,feed_dict={x:inp}))
    print(result.astype(np.int64))

iteration=  0 cost=  1.67627
iteration=  1000 cost=  0.270833
iteration=  2000 cost=  0.226531
iteration=  3000 cost=  0.19822
iteration=  4000 cost=  0.176083
iteration=  5000 cost=  0.15827
iteration=  6000 cost=  0.143683
iteration=  7000 cost=  0.131538
iteration=  8000 cost=  0.121273
iteration=  9000 cost=  0.112479
iteration=  10000 cost=  0.104858
iteration=  11000 cost=  0.0981871
iteration=  12000 cost=  0.0922962
Validating output for OR GATE
[[0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [15]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,3])
y=tf.placeholder(tf.float32,shape=[None,1])

weights1=tf.Variable(tf.random_normal([3,3]),dtype=tf.float32)
bias1=tf.Variable(tf.random_normal([3]),dtype=tf.float32)

weights2=tf.Variable(tf.random_normal([3,1]),dtype=tf.float32)
bias2=tf.Variable(tf.random_normal([1]),dtype=tf.float32)


multiply1=tf.add(tf.matmul(x,weights1),bias1)
z=tf.nn.sigmoid(multiply1)

multiply2=tf.add(tf.matmul(z,weights2),bias2)
z1=tf.nn.sigmoid(multiply2)

cost=tf.reduce_mean((y*tf.log(z1)+(1-y)*tf.log(1-z1))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.2).minimize(cost)

inp=np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
op=np.array([[0],[1],[1],[0],[1],[0],[0],[1]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(13001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for XOR GATE")
    result=np.around(sess.run(z1,feed_dict={x:inp}))
    print (result.astype(np.int64))

iteration=  0 cost=  0.860419
iteration=  1000 cost=  0.692637
iteration=  2000 cost=  0.649987
iteration=  3000 cost=  0.447318
iteration=  4000 cost=  0.164562
iteration=  5000 cost=  0.0641247
iteration=  6000 cost=  0.0391043
iteration=  7000 cost=  0.0281482
iteration=  8000 cost=  0.0220061
iteration=  9000 cost=  0.0180745
iteration=  10000 cost=  0.0153405
iteration=  11000 cost=  0.0133285
iteration=  12000 cost=  0.0117854
iteration=  13000 cost=  0.0105641
Validating output for XOR GATE
[[0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]]


In [17]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,3])
y=tf.placeholder(tf.float32,shape=[None,1])

weights1=tf.Variable(tf.random_normal([3,3]),dtype=tf.float32)
bias1=tf.Variable(tf.random_normal([3]),dtype=tf.float32)

weights2=tf.Variable(tf.random_normal([3,1]),dtype=tf.float32)
bias2=tf.Variable(tf.random_normal([1]),dtype=tf.float32)


multiply1=tf.add(tf.matmul(x,weights1),bias1)
z=tf.nn.sigmoid(multiply1)

multiply2=tf.add(tf.matmul(z,weights2),bias2)
z1=tf.nn.sigmoid(multiply2)

cost=tf.reduce_mean((y*tf.log(z1)+(1-y)*tf.log(1-z1))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.2).minimize(cost)

inp=np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
op=np.array([[1],[0],[0],[1],[0],[1],[1],[0]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(14001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for XNOR GATE")
    result=np.around(sess.run(z1,feed_dict={x:inp}))
    print (result.astype(np.int64))

iteration=  0 cost=  0.713619
iteration=  1000 cost=  0.693104
iteration=  2000 cost=  0.691728
iteration=  3000 cost=  0.63166
iteration=  4000 cost=  0.315386
iteration=  5000 cost=  0.106572
iteration=  6000 cost=  0.0486977
iteration=  7000 cost=  0.0302815
iteration=  8000 cost=  0.0217065
iteration=  9000 cost=  0.0168239
iteration=  10000 cost=  0.0136934
iteration=  11000 cost=  0.011524
iteration=  12000 cost=  0.00993586
iteration=  13000 cost=  0.00872501
iteration=  14000 cost=  0.0077724
Validating output for XNOR GATE
[[1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]]
